<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="bin\Debug\rectangle.jpg" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\oval.png" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\rhomb.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Neo4j.Driver" Version="5.20.0" />
  </ItemGroup>

</Project>